/**
 * SKILL SETU — Phase 4 controlled DEMO opportunities (master spec §52).
 *
 * All opportunity skills reference the SAME centralized skillIds from Phase 3.
 * Deadlines are set relative to the demo timeline (Sept 2026) so the deadline
 * intelligence (Open / Closing Soon / Closed) demonstrates correctly.
 */

import { SKILL_IDS } from "@/lib/intelligence/role-config";
import { skillName as skillNameOf } from "@/lib/intelligence/demo-data";
import type { Opportunity } from "./opportunity-model";

const s = SKILL_IDS;

function req(skillId: string, requiredLevel: number, importance = 1) {
  return { skillId, skillName: skillNameOf(skillId), importance, requiredLevel };
}

// Demo timeline: "today" is treated as ~18 Sept 2026 for deadline logic.
// Deadlines: some closing soon (within 7 days), some open (weeks away), one closed (past).
const D = (daysFromDemoToday: number) => {
  const base = new Date("2026-09-18T00:00:00");
  base.setDate(base.getDate() + daysFromDemoToday);
  return base.toISOString().slice(0, 10);
};

export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-ds-intern",
    title: "Data Science Intern",
    company: "Nova Analytics",
    organizationType: "Product Company",
    description: "Join Nova Analytics as a Data Science Intern to work on real-world analytics pipelines, model prototyping and stakeholder reporting.",
    type: "INTERNSHIP",
    location: "Pune",
    mode: "Hybrid",
    duration: "6 Months",
    compensationType: "Stipend",
    compensationAmount: "₹35,000/mo",
    applicationDeadline: D(12),
    startDate: "2026-10-15",
    endDate: "2027-04-15",
    requiredSkills: [req(s.python, 70, 1), req(s.sql, 60, 0.8), req(s.machineLearning, 70, 1), req(s.statistics, 60, 0.8)],
    preferredSkills: [req(s.problemSolving, 60, 0.5)],
    targetRoles: ["data-scientist"],
    eligibilityRules: { yearMin: 2, cgpaMin: 7.0, requiredRoleIds: ["data-scientist"] },
    responsibilities: ["Build and evaluate ML prototypes", "Query and model data in SQL", "Present findings to stakeholders", "Document reproducible notebooks"],
    qualifications: ["B.Tech/M.Tech in CS/AI/DS", "Year 2+", "Python proficiency"],
    benefits: ["Mentorship", "Pre-placement offer consideration", "Certification on completion"],
    status: "Published",
    createdAt: "2026-09-10T10:00:00",
    updatedAt: "2026-09-10T10:00:00",
  },
  {
    id: "opp-ml-intern",
    title: "ML Engineering Intern",
    company: "Vertex Labs",
    organizationType: "AI/ML Research",
    description: "Fine-tune LLMs and build evaluation pipelines for document AI at Vertex Labs.",
    type: "INTERNSHIP",
    location: "Bengaluru",
    mode: "On-site",
    duration: "3 Months",
    compensationType: "Stipend",
    compensationAmount: "₹40,000/mo",
    applicationDeadline: D(5),
    requiredSkills: [req(s.python, 75, 1), req(s.machineLearning, 70, 1), req(s.deepLearning, 65, 0.9)],
    preferredSkills: [req(s.mathStatistics, 60, 0.5)],
    targetRoles: ["ml-engineer"],
    eligibilityRules: { yearMin: 3, cgpaMin: 7.5, requiredRoleIds: ["ml-engineer", "data-scientist"] },
    responsibilities: ["Run experiments", "Document results", "Build evaluation harnesses"],
    qualifications: ["Year 3+ CS/AI", "ML fundamentals"],
    benefits: ["Research publication opportunity", "Stipend"],
    status: "Published",
    createdAt: "2026-09-08T09:00:00",
    updatedAt: "2026-09-08T09:00:00",
  },
  {
    id: "opp-fs-project",
    title: "Full Stack Project — Campus Ops Platform",
    company: "TechBridge",
    organizationType: "Startup",
    description: "Build an end-to-end campus operations platform with React frontend and Node backend.",
    type: "PROJECT",
    location: "Remote",
    mode: "Remote",
    duration: "8 Weeks",
    compensationType: "Stipend",
    compensationAmount: "₹15,000",
    applicationDeadline: D(20),
    problem: "Campuses lack a unified operations dashboard for events, clubs and facilities.",
    teamSize: "3-4",
    mentor: "Ankit Verma (TechBridge)",
    requiredSkills: [req(s.frontend, 70, 1), req(s.backend, 70, 1), req(s.databaseMgmt, 60, 0.8), req(s.apiIntegration, 60, 0.8)],
    preferredSkills: [req(s.problemSolving, 70, 0.5)],
    targetRoles: ["full-stack-developer"],
    eligibilityRules: { yearMin: 2 },
    responsibilities: ["Design the frontend", "Build REST APIs", "Model the database", "Deploy"],
    qualifications: ["Year 2+", "Full-stack basics"],
    benefits: ["Mentorship", "Project certificate", "Stipend"],
    status: "Published",
    createdAt: "2026-09-05T14:00:00",
    updatedAt: "2026-09-05T14:00:00",
  },
  {
    id: "opp-jr-ds-job",
    title: "Junior Data Scientist",
    company: "Nova Analytics",
    organizationType: "Product Company",
    description: "Full-time role building and shipping data products at Nova Analytics.",
    type: "JOB",
    location: "Pune",
    mode: "Hybrid",
    duration: "Full-time",
    compensationType: "Salary",
    compensationAmount: "₹12 LPA",
    applicationDeadline: D(25),
    requiredSkills: [req(s.python, 75, 1), req(s.sql, 70, 0.8), req(s.machineLearning, 70, 1), req(s.statistics, 65, 0.8)],
    preferredSkills: [req(s.problemSolving, 70, 0.5)],
    targetRoles: ["data-scientist"],
    eligibilityRules: { yearMin: 4, cgpaMin: 7.5, requiredRoleIds: ["data-scientist"] },
    responsibilities: ["Own data products", "Build ML pipelines", "Mentor interns"],
    qualifications: ["B.Tech/M.Tech", "Final year or graduate"],
    benefits: ["Health insurance", "ESOPs", "Learning budget"],
    status: "Published",
    createdAt: "2026-09-12T11:00:00",
    updatedAt: "2026-09-12T11:00:00",
  },
  {
    id: "opp-be-job",
    title: "Backend Engineer",
    company: "TechNova Solutions",
    organizationType: "SaaS",
    description: "Build scalable backend services and APIs at TechNova.",
    type: "JOB",
    location: "Remote",
    mode: "Remote",
    duration: "Full-time",
    compensationType: "Salary",
    compensationAmount: "₹10 LPA",
    applicationDeadline: D(28),
    requiredSkills: [req(s.programming, 75, 1), req(s.dsa, 70, 0.9), req(s.databaseMgmt, 65, 0.8), req(s.softwareEngineering, 65, 0.8)],
    preferredSkills: [req(s.problemSolving, 70, 0.5)],
    targetRoles: ["software-engineer"],
    eligibilityRules: { yearMin: 4, cgpaMin: 7.0 },
    responsibilities: ["Design APIs", "Optimise databases", "Build microservices"],
    qualifications: ["B.Tech CS", "Final year or graduate"],
    benefits: ["Remote-first", "Learning budget"],
    status: "Published",
    createdAt: "2026-09-11T10:00:00",
    updatedAt: "2026-09-11T10:00:00",
  },
  {
    id: "opp-de-intern",
    title: "Data Engineering Intern",
    company: "CloudPeak Systems",
    organizationType: "Cloud/DevOps",
    description: "Build data pipelines on the cloud and learn production data engineering.",
    type: "INTERNSHIP",
    location: "Pune",
    mode: "Hybrid",
    duration: "4 Months",
    compensationType: "Stipend",
    compensationAmount: "₹35,000/mo",
    applicationDeadline: D(40),
    requiredSkills: [req(s.python, 65, 0.9), req(s.sql, 65, 1), req(s.cloudPlatforms, 55, 0.8)],
    preferredSkills: [req(s.dockerK8s, 50, 0.5)],
    targetRoles: ["devops-engineer", "data-scientist"],
    eligibilityRules: { yearMin: 2 },
    responsibilities: ["ETL pipelines", "Data modelling", "Cloud deployment"],
    qualifications: ["Year 2+", "Python + SQL"],
    benefits: ["Cloud certification support", "Stipend"],
    status: "Published",
    createdAt: "2026-09-09T12:00:00",
    updatedAt: "2026-09-09T12:00:00",
  },
  {
    id: "opp-ml-cert",
    title: "Applied Machine Learning Specialization",
    company: "Coursera",
    organizationType: "Online Learning",
    description: "A project-based ML specialisation covering supervised, unsupervised and deep learning.",
    type: "CERTIFICATION",
    location: "Online",
    mode: "Online",
    duration: "8 Weeks",
    compensationType: "Free",
    applicationDeadline: D(60),
    provider: "Coursera",
    requiredSkills: [req(s.machineLearning, 0, 1)],
    preferredSkills: [req(s.python, 50, 0.5)],
    targetRoles: ["data-scientist", "ml-engineer"],
    eligibilityRules: {},
    responsibilities: ["Complete weekly modules", "Submit capstone project"],
    qualifications: ["Basic Python"],
    benefits: ["Certificate", "Portfolio project"],
    status: "Published",
    createdAt: "2026-09-01T08:00:00",
    updatedAt: "2026-09-01T08:00:00",
  },
  {
    id: "opp-sql-workshop",
    title: "Advanced SQL Workshop",
    company: "DataForge Labs",
    organizationType: "Workshop",
    description: "Hands-on advanced SQL case studies — window functions, CTEs, query optimisation.",
    type: "WORKSHOP",
    location: "Online",
    mode: "Online",
    duration: "2 Days",
    compensationType: "Free",
    applicationDeadline: D(3),
    provider: "DataForge Labs",
    requiredSkills: [req(s.sql, 40, 1)],
    targetRoles: ["data-scientist", "software-engineer", "full-stack-developer"],
    eligibilityRules: {},
    responsibilities: ["Attend live sessions", "Complete exercises"],
    qualifications: ["Basic SQL"],
    benefits: ["Workshop certificate"],
    status: "Published",
    createdAt: "2026-09-14T09:00:00",
    updatedAt: "2026-09-14T09:00:00",
  },
  {
    id: "opp-ds-mentorship",
    title: "Industry Mentorship: Data Science",
    company: "Nova Analytics",
    organizationType: "Mentorship",
    description: "1-on-1 mentorship with a senior data scientist at Nova Analytics.",
    type: "MENTORSHIP",
    location: "Hybrid",
    mode: "Hybrid",
    duration: "12 Weeks",
    compensationType: "Free",
    applicationDeadline: D(15),
    provider: "Nova Analytics",
    requiredSkills: [req(s.python, 60, 0.8), req(s.machineLearning, 50, 1), req(s.statistics, 50, 0.8)],
    targetRoles: ["data-scientist"],
    eligibilityRules: { requiredRoleIds: ["data-scientist"] },
    responsibilities: ["Bi-weekly mentor sessions", "Career guidance", "Project reviews"],
    qualifications: ["Targeting Data Scientist role"],
    benefits: ["Career guidance", "Industry exposure"],
    status: "Published",
    createdAt: "2026-09-07T10:00:00",
    updatedAt: "2026-09-07T10:00:00",
  },
  {
    id: "opp-cloud-training",
    title: "Cloud & DevOps for ML",
    company: "CloudPeak Systems",
    organizationType: "Training",
    description: "Deploy ML services to the cloud end-to-end — Docker, Kubernetes, CI/CD.",
    type: "TRAINING",
    location: "Online",
    mode: "Online",
    duration: "6 Weeks",
    compensationType: "Paid",
    compensationAmount: "₹5,000",
    applicationDeadline: D(-5), // CLOSED (past deadline) — demonstrates Closed status
    provider: "CloudPeak Systems",
    requiredSkills: [req(s.cloudPlatforms, 50, 1), req(s.dockerK8s, 50, 1), req(s.python, 50, 0.5)],
    targetRoles: ["devops-engineer", "ml-engineer"],
    eligibilityRules: { yearMin: 2 },
    responsibilities: ["Complete modules", "Deploy a sample ML service"],
    qualifications: ["Year 2+", "Basic Python"],
    benefits: ["Training certificate"],
    status: "Published",
    createdAt: "2026-08-20T08:00:00",
    updatedAt: "2026-08-20T08:00:00",
  },
];

export function findOpportunity(id: string): Opportunity | undefined {
  return DEMO_OPPORTUNITIES.find((o) => o.id === id);
}
