/**
 * SKILL SETU — Phase 10 Evaluator Demo Engine.
 *
 * Orchestrates the canonical demo journey (§3) by calling EXISTING Phase 3-8
 * Zustand store actions. NO duplicate scoring engines, NO duplicate mock data,
 * NO duplicate student/skill/opportunity models (master spec §1, §20, §80).
 *
 * The cross-portal propagation happens AUTOMATICALLY through the shared stores:
 *  - useIntelligence (Phase 3) — student, competencies, evidence, readiness
 *  - useCareerStore (Phase 4) — opportunities, applications, matching
 *  - useIndustryStore (Phase 5) — feedback, challenges, candidates
 *  - useAcademiaStore (Phase 6) — collaborations, mentorship
 *  - useInstitutionStore (Phase 7) — interventions, alerts
 *  - useHackathonStore (Phase 8) — registrations, teams
 *
 * Master spec §21 (deterministic calculations), §63 (rules calculate, AI explains).
 */

import { useDemoStore } from "./demo-store";
import { useIntelligence } from "@/lib/intelligence";
import { useCareerStore } from "@/lib/career/store";
import { useIndustryStore } from "@/lib/industry/industry-store";
import { useAcademiaStore } from "@/lib/academia/academia-store";
import { useInstitutionStore } from "@/lib/institution/institution-store";
import { useHackathonStore } from "@/lib/hackathon/hackathon-store";
import type { EvidenceStatus } from "@/lib/intelligence/types";

// S042 baseline competencies (matches DEMO_ROLE_PROFILES.data-scientist)
const S042_BASELINE = {
  python: 82,
  sql: 64,
  statistics: 51,
  machineLearning: 43,
  problemSolving: 75,
};

// Skill IDs (must match Phase 3 SKILL_IDS)
const SKILL_IDS = {
  python: "python",
  sql: "sql",
  statistics: "statistics",
  machineLearning: "machine-learning",
  problemSolving: "problem-solving",
};

export const DemoEngine = {
  /**
   * §2 — Start demo mode. Activates the demo store + records the start event.
   * Underlying stores are NOT reset (preserves user state) — use resetDemo() for that.
   */
  startDemo: () => {
    useDemoStore.getState().startDemo();
  },

  /**
   * §23 — Reset demo to baseline. Resets ALL underlying stores to their initial state.
   * This is the "Reset Demo" button.
   */
  resetDemo: () => {
    // Reset each underlying store to its baseline
    useIntelligence.getState().resetAll();
    useCareerStore.getState().resetCareer?.();
    useIndustryStore.getState().resetIndustry();
    useAcademiaStore.getState().resetAcademia?.();
    useInstitutionStore.getState().resetInstitution();
    useHackathonStore.getState().resetHackathon?.();

    // Reset the demo store state
    useDemoStore.getState().resetDemoState();
  },

  /**
   * §8 — Generate New Evidence (the CRITICAL demo action).
   * Simulates S042 completing the recommended Machine Learning project.
   * Creates a new EvidenceRecord (status: Submitted) for S042 in the
   * shared intelligence store. The shared engine then AUTOMATICALLY:
   *  - adds the evidence to S042's evidence pipeline
   *  - recomputes evidence confidence for ML
   *  - (readiness/gap/match recalculation happens on verifyEvidence)
   *
   * This is DEMO/SYNTHETIC data — clearly labelled.
   */
  generateNewEvidence: (): string | null => {
    const intel = useIntelligence.getState();
    const demo = useDemoStore.getState();

    // Create the new evidence record (Customer Churn Prediction project)
    // covering ML + Python + Statistics
    const skillsToAdd = [
      { skillId: SKILL_IDS.machineLearning, skillName: "Machine Learning" },
      { skillId: SKILL_IDS.python, skillName: "Python" },
      { skillId: SKILL_IDS.statistics, skillName: "Statistics" },
    ];

    let primaryEvidenceId: string | null = null;
    for (const s of skillsToAdd) {
      const evidenceId = intel.addEvidence({
        skillId: s.skillId,
        skillName: s.skillName,
        sourceType: "Project",
        sourceTitle: "Customer Churn Prediction Project",
        score: null, // unscored submission initially
        status: "Submitted",
        verificationStatus: "Pending",
        description:
          "End-to-end ML project: Customer Churn Prediction. Skills demonstrated — feature engineering, model selection (logistic regression, random forest, XGBoost), cross-validation, evaluation. GitHub repository submitted with notebook + README. DEMO/SYNTHETIC evidence generated by Evaluator Demo Mode.",
        reference: "https://github.com/demo-s042/customer-churn-prediction",
      });
      if (s.skillId === SKILL_IDS.machineLearning && !primaryEvidenceId) {
        primaryEvidenceId = evidenceId;
      }
    }

    if (primaryEvidenceId) {
      demo.setNewEvidenceId(primaryEvidenceId);
    }

    // Record demo events — the propagation story
    demo.recordEvent({
      actor: "Student Portal",
      action: "S042 submitted Customer Churn Prediction project evidence",
      affectedEntity: "S042 · Machine Learning / Python / Statistics",
      category: "Evidence Generated",
      affectedModules: ["Skill Profile", "Evidence Pipeline", "Skill Passport"],
      explanation:
        "S042 completed the recommended applied Machine Learning project. New evidence record created (status: Submitted) for Machine Learning, Python and Statistics. The evidence pipeline now shows the new entry at the top. Competency scores have NOT changed yet — verification is required first. This is DEMO/SYNTHETIC data generated by the Evaluator Demo Mode.",
    });

    demo.recordEvent({
      actor: "Skill Intelligence Engine",
      action: "Added new evidence to S042's evidence pipeline",
      affectedEntity: "S042 · Customer Churn Prediction Project",
      category: "Evidence Generated",
      affectedModules: ["Evidence Pipeline", "Skill Passport"],
      explanation:
        "The new project evidence was added to S042's evidence pipeline. The Skill Passport will now display this entry under Projects. Evidence confidence for Machine Learning will recompute once the evidence is verified.",
    });

    return primaryEvidenceId;
  },

  /**
   * §10 — Verify / Evaluate Evidence.
   * Transitions the new evidence from Submitted → Evaluated → Verified.
   * After verification, bumps the ML competency (since verified project evidence
   * demonstrates capability). Then the shared engine AUTOMATICALLY recalculates:
   *  - role readiness (via useIntelligenceDerived hook)
   *  - skill gaps (via calculateSkillGaps)
   *  - opportunity match (via useCareer/useIndustry hooks)
   *  - next best action (via getNextBestAction)
   *  - institution aggregate (via useInstitution hook)
   */
  verifyEvidence: (): { verified: boolean; newMlCompetency: number; oldMlCompetency: number } => {
    const intel = useIntelligence.getState();
    const demo = useDemoStore.getState();
    const newEvidenceId = demo.newEvidenceId;

    if (!newEvidenceId) {
      return { verified: false, newMlCompetency: 0, oldMlCompetency: 0 };
    }

    // Get the old ML competency before verification
    const oldMlCompetency = intel.competencies[SKILL_IDS.machineLearning]?.competencyScore ?? S042_BASELINE.machineLearning;

    // Transition: Submitted → Evaluated → Verified
    const statusTransition: EvidenceStatus = "Verified";
    intel.updateEvidenceStatus(newEvidenceId, statusTransition);

    // Also verify the Python + Statistics evidence records from the same project
    // (they have the same sourceTitle "Customer Churn Prediction Project")
    const projectEvidence = intel.evidence.filter(
      (e) => e.sourceTitle === "Customer Churn Prediction Project" && e.status === "Submitted",
    );
    for (const e of projectEvidence) {
      intel.updateEvidenceStatus(e.evidenceId, "Verified");
    }

    // Bump the ML competency based on verified project evidence.
    // Per §21 (deterministic) + §11 (readiness must mathematically change):
    // - Verified project evidence demonstrates ~+20 competency points (capped at 90)
    // - This is consistent with the existing evidence-confidence model that
    //   uses verified evidence as a strong signal
    const verifiedProjectEvidence = intel.evidence.filter(
      (e) =>
        e.skillId === SKILL_IDS.machineLearning &&
        e.status === "Verified" &&
        e.sourceType === "Project",
    );
    const verifiedCount = verifiedProjectEvidence.length;
    // +20 per verified project, capped at 90
    const bump = Math.min(20 * verifiedCount, 90 - oldMlCompetency);
    const newMlCompetency = Math.max(oldMlCompetency, Math.min(90, oldMlCompetency + bump));

    if (bump > 0) {
      intel.setCompetency(SKILL_IDS.machineLearning, newMlCompetency);
    }

    // Record demo events — the propagation story continues
    demo.recordEvent({
      actor: "Skill Intelligence Engine",
      action: "Evidence verified — Customer Churn Prediction Project",
      affectedEntity: "S042 · Machine Learning",
      category: "Evidence Verified",
      affectedModules: ["Evidence Pipeline", "Skill Profile"],
      explanation:
        "Industry/faculty verification completed. The Customer Churn Prediction project evidence transitioned from Submitted → Evaluated → Verified. Evidence confidence for Machine Learning increased because verified project evidence is a strong signal in the existing evidence-confidence model.",
    });

    demo.recordEvent({
      actor: "Skill Intelligence Engine",
      action: "Recalculated Machine Learning competency",
      affectedEntity: "S042 · Machine Learning",
      category: "Readiness Recalculated",
      affectedModules: ["Skill Profile", "Role Readiness", "Skill Gap"],
      explanation: `Machine Learning competency updated from ${oldMlCompetency} to ${newMlCompetency} based on ${verifiedCount} verified project evidence record(s). The competency bump is deterministic: +20 points per verified project (capped at 90). This is the ONLY competency change — all other skills remain at baseline.`,
    });

    demo.recordEvent({
      actor: "Skill Intelligence Engine",
      action: "Recalculated Data Scientist role readiness for S042",
      affectedEntity: "S042 · Data Scientist",
      category: "Readiness Recalculated",
      affectedModules: ["Role Readiness", "Skill Gap"],
      explanation: `Role readiness recalculated using the existing formula: readiness = Σ(studentCompetency × roleWeight) / Σ(roleWeight). Machine Learning has 30% weight in the Data Scientist role config, so the ${bump}-point ML competency bump produces a measurable readiness change. The useIntelligenceDerived hook in the Student Portal recomputes automatically.`,
    });

    demo.recordEvent({
      actor: "Skill Intelligence Engine",
      action: "Recalculated skill gaps for S042",
      affectedEntity: "S042 · Machine Learning gap reduced",
      category: "Skill Gap Recalculated",
      affectedModules: ["Skill Gap", "Next Best Action"],
      explanation: `Skill gaps recalculated using the existing calculateSkillGaps engine. Machine Learning gap is now reduced/resolved (was 43, now ${newMlCompetency}). Statistics (51) remains a gap. The next best action may shift from "Build ML project" to "Strengthen Statistics".`,
    });

    demo.recordEvent({
      actor: "Opportunity Match Engine",
      action: "Recalculated opportunity match for S042",
      affectedEntity: "S042 · Data Science Internship",
      category: "Match Recalculated",
      affectedModules: ["Opportunity Match", "Industry Talent Discovery"],
      explanation:
        "The Phase 4 matching engine (calculateOpportunityMatch) automatically recomputed S042's match against the Data Science Internship opportunity. The 40% skill-alignment component of the match formula now reflects the increased ML competency. The Industry Talent Discovery view will show the updated match score.",
    });

    demo.recordEvent({
      actor: "Institution Portal",
      action: "Institution aggregate insight updated",
      affectedEntity: "AI & Data Science · Machine Learning",
      category: "Institution Insight Updated",
      affectedModules: ["Institution Insights", "Demand vs Supply", "Branch × Skill"],
      explanation:
        "The Institution portal's useInstitution hook recomputed demand vs supply. Machine Learning supply (average competency across candidates including S042) increased, narrowing the demand-supply gap. The Branch × Skill heatmap and intervention recommendations auto-updated.",
    });

    return { verified: true, newMlCompetency, oldMlCompetency };
  },

  /**
   * §14 — Submit Industry Feedback.
   * Calls the EXISTING useIndustryStore.submitFeedback which:
   *  - creates an IndustryFeedback record
   *  - creates EvidenceRecord(s) in the Phase 3 intelligence store (cross-portal!)
   *  - fires notifications
   *
   * Uses the ACTUAL IndustryFeedback model shape (not the spec's example):
   *  - experience: string
   *  - technicalFeedback, professionalFeedback, strengths, areasForImprovement
   *  - skillScores: { skillId, skillName, score }[]
   *  - categoryScores: { category: FeedbackCategory, score }[]
   */
  submitIndustryFeedback: (): string | null => {
    const industry = useIndustryStore.getState();
    const demo = useDemoStore.getState();
    const industryUser = industry.user;

    // Submit feedback for S042's Customer Churn Prediction project
    const feedbackId = industry.submitFeedback({
      studentId: "S042",
      studentName: "Aarav Sharma",
      experience: "Customer Churn Prediction Project",
      technicalFeedback: "Strong end-to-end ML pipeline. Good feature engineering and model selection. Documentation could be more detailed.",
      professionalFeedback: "Professional delivery, timely submission. Communication clear throughout the project. Strong team fit.",
      strengths: "End-to-end ML execution, feature engineering, model comparison (logistic regression vs random forest vs XGBoost), cross-validation rigour.",
      areasForImprovement: "Documentation could be more detailed. Consider adding model interpretability section (SHAP/LIME).",
      skillScores: [
        { skillId: SKILL_IDS.machineLearning, skillName: "Machine Learning", score: 4 },
        { skillId: SKILL_IDS.python, skillName: "Python", score: 4 },
        { skillId: SKILL_IDS.statistics, skillName: "Statistics", score: 4 },
      ],
      categoryScores: [
        { category: "Technical", score: 4 },
        { category: "Problem Solving", score: 4 },
        { category: "Communication", score: 4 },
        { category: "Teamwork", score: 4 },
        { category: "Leadership", score: 3 },
        { category: "Professionalism", score: 5 },
      ],
    });

    demo.setFeedbackId(feedbackId);

    // Record demo events — the feedback propagation story
    demo.recordEvent({
      actor: "Industry Portal",
      action: "Industry submitted project evaluation feedback for S042",
      affectedEntity: "S042 · Customer Churn Prediction Project",
      category: "Feedback Submitted",
      affectedModules: ["Industry Feedback", "Skill Profile", "Skill Passport"],
      explanation: `Industry (${industryUser.organization}) submitted feedback for S042's Customer Churn Prediction project. Technical 4/5, Problem Solving 4/5, Communication 4/5, Teamwork 4/5, Leadership 3/5, Professionalism 5/5. The existing submitFeedback flow creates evidence records in the shared intelligence store for each scored skill (Phase 5 §32 feedback→evidence loop).`,
    });

    demo.recordEvent({
      actor: "Skill Intelligence Engine",
      action: "Feedback propagated to evidence — S042 skill profile updated",
      affectedEntity: "S042 · Machine Learning / Python / Statistics",
      category: "Passport Updated",
      affectedModules: ["Skill Profile", "Skill Passport", "Evidence Pipeline"],
      explanation:
        "The industry feedback created new evidence records (sourceType: IndustryFeedback, status: Evaluated) for ML, Python and Statistics in the shared intelligence store. The Skill Passport now displays the industry evaluation under the Customer Churn Prediction project. Evidence confidence for the affected skills recomputed automatically.",
    });

    demo.recordEvent({
      actor: "Academia Portal",
      action: "Academia signal updated — ML practical evidence improving",
      affectedEntity: "Machine Learning · Industry signal",
      category: "Academia Signal Updated",
      affectedModules: ["Industry Signal", "Curriculum Alignment", "Practical Exposure"],
      explanation:
        "The Academia portal's useAcademia hook recomputed industry signals and curriculum alignment. Machine Learning practical evidence for the cohort improved (one more verified project + industry feedback). The curriculum alignment status may shift from 'Needs Attention' to 'Aligned' if enough cohort evidence accumulates.",
    });

    return feedbackId;
  },

  /**
   * §4 — Industry updates role requirements.
   * (Optional demo action — calls existing createDemand on industry store.)
   * For now this is a no-op placeholder; the canonical demo journey focuses on
   * generateEvidence → verify → feedback.
   */
  updateRoleRequirements: () => {
    const demo = useDemoStore.getState();
    demo.recordEvent({
      actor: "Industry Portal",
      action: "Industry updated Data Scientist role requirements",
      affectedEntity: "Data Scientist · role weights",
      category: "Demand Change",
      affectedModules: ["Role Requirements", "Role Readiness Context", "Opportunity Match Context"],
      explanation:
        "Industry updated the role requirements. The shared role-config is the source of truth — the readiness calculation context, opportunity matching context and recommended candidates context all reference the same role weights. (In the canonical demo journey, this is an optional step before the generateEvidence action.)",
    });
  },
};
